# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
# 1
  desc "Create app on Apple Developer and App Store Connect sites"
# 2
  lane :create_app do
# 3
​    produce
  end
end

lane:lint do
swiftlint(
  mode: :lint,      # SwiftLint mode: :lint (default) or :autocorrect
  output_file: "swiftlint.result.json", # The path of the output file (optional)
  files: [# List of files to process (optional)
    "./NewYorkTopStories/Delegate/AppDelegate.swift",
    "./NewYorkTopStories/Model/Articles.swift"
  ],
  ignore_exit_status: true    # Allow fastlane to continue even if SwiftLint returns a non-zero exit status
)
end

lane :tests do
  run_tests(scheme: "NewYorkTopStoriesTests")
end

desc "Take screenshots"
  lane :screenshot do
    snapshot
  end

desc "Create ipa"
  lane :build do
    # 1
    enable_automatic_code_signing
    # 2
    increment_build_number
    # 3
    gym
  end

desc "Upload to App Store"
  lane :upload do
    deliver
  end

   desc “Create app, take screenshots, build and upload to App Store"
  lane :run_lanes do
    lint
    tests
    screenshot
    build
    upload
  end

